AWSTemplateFormatVersion: '2010-09-09'
Description: 'Parent Stack for the specified environment'

Parameters:
  TemplateUrlBase:
    Type: String
    Default: 'https://cfn-templates-github-actions.s3.eu-west-2.amazonaws.com/environments'
    
  Environment:
    Description: List of available environments
    Type: String
    AllowedValues:
      - dev
      - staging
      - production
    Default: dev

Resources:
  NetworkStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub '${TemplateUrlBase}/${Environment}/network.yaml'
      Parameters:
        Environment: !Ref Environment

  ComputeStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub '${TemplateUrlBase}/${Environment}/compute.yaml'
      Parameters:
        Environment: !Ref Environment
        MyPublicSubnet: !GetAtt NetworkStack.Outputs.MyPublicSubnet
        InstanceSecurityGroup: !GetAtt NetworkStack.Outputs.InstanceSecurityGroup

       