name: AWS CloudFormation CI/CD using GitHub Actions

on:
  push:
    branches:
      - '*'
  #workflow_dispatch:
  

env:
  AWS_REGION:  ${{ vars.AWS_REGION }}
  BUCKET_NAME: ct-cfn-files-for-stack-github-actions

jobs:

  create_bucket:
    name: Create S3 Bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy bucket stack
        run: |
          echo $AWS_REGION